### ISSUE TITLE
Give a way of changing mode-line font

### ISSUE THREAD

**Issue by ghost** [ozanvos/emacs-afternoon-theme#1]
Hi, nice theme! I'm missing a simple way of customizing the mode-line font, for example something like:

``` lisp
(setq afternoon-mode-line-font-family "Hermit")
```

What do you think?

**Comment by ozanvos** [comment]
You can use something like this:

``` el
(custom-set-faces '(mode-line ((t (:family "Hermit")))))
```

Let me know if that works for you.

**Comment by ghost** [comment]
It worked! sorry for bothering you with such a foolish thing ;)

**Comment by ozanvos** [comment]
Cool, glad it worked out :)

**Comment by mpolden** [comment]
You can also set the font to unspecified, which will make the mode-line inherit your default font.

``` lisp
(set-face-attribute 'mode-line nil
                    :family 'unspecified)
```

**Comment by toctan** [comment]
@osener It's a beautiful theme. Thanks! May I ask you what font do you use in the screenshot?

**Comment by ozanvos** [comment]
@toctan, Thanks! It's [Akkurat Mono](http://lineto.com/The+Fonts/Font+Categories/Text+Fonts/Akkurat+Mono/), great font but unfortunately it's quite pricey.
