### ISSUE TITLE
Terminal background colors issue

### ISSUE THREAD

**Issue by dakrone** [ozanvos/emacs-afternoon-theme#2]
Is there a way to get the background to be the same for the terminal as the GUI?

GUI Screenshot: http://i.imgur.com/eWrjUTe.png
Terminal Screenshot: http://i.imgur.com/9Cir5LA.png

**Comment by ozanvos** [comment]
Unfortunately I don't think this is possible under a 256 color terminal (see `M-x list-colors-display`), although I'd love to be proven wrong.

Maybe this could be worked around by falling back to ANSI colors and asking users to set their terminal emulator's colorscheme by applying a provided Xdefaults/.itermcolors, but I'm not sure it would be worth the effort.

**Comment by ozanvos** [comment]
Just pushed a workaround for this. The Emacs version I'm using, emacs-mac-port, doesn't allow connecting to servers created by GUI Emacs from a terminal instance and vice-versa, so I can't test if the fix works in that case (it might even break the theme when doing the opposite) so please let me know if it works for you or if you have a better idea.

**Comment by dakrone** [comment]
It's closer, but kind of makes org-mode files look very ugly right now :)

See: http://i.imgur.com/MTOe6kO.png

**Comment by ozanvos** [comment]
Sorry for the delay, please let me know if you spot any other issue.

**Comment by dakrone** [comment]
Seems to work; thanks!

**Comment by freehck** [comment]
@osener 

Have just tested afternoon-theme on classical Emacs 28.1 in daemon mode.

This fix doesn't work. As you correctly noted it definitely breaks the colors when you use terminal and GUI emacsclients at the same time as theme colors are evaluated to different values for different frames. And theme colors are global across the frames.

When I start the GUI emacs daemon it's >256 colors. So when I attach a terminal emacsclient (iterm2, 256 colors) to the daemon, I see blue background. If I load theme from it, the colours will be normal. If I attach then a GUI emacsclient and load the theme from there, I will immediately turn the background colour of all the terminal emacsclients back to blue.

PS: I'm not going to test it anymore. I just keep you informed that the problem still exists (despite the fact it was closed in 2014).
